# fly.toml app configuration file generated for railway-sshh-qbxzfq on 2025-11-09T15:40:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "railway-sshh-qbxzfq"
primary_region = "iad"

# Dịch vụ chính: SSH qua TCP
[[services]]
  internal_port = 22
  protocol = "tcp"

  [[services.ports]]
    port = 22

[[vm]]
  cpu_kind = "shared"
  cpus = 4
  memory_mb = 4096
